#________________________________________________________________
# ****** Дополнительные настройки ******
# При запуске запустит для всех сайтов указанное количество потоков у каждого сервиса.
# Если хотите отключить один из сайтов просто поставьте threads_count:0 для нужного сайта


# Браузер для запуска : Firefox | Chrome
# На выбор что у вас быстрее работает
webdriver: Chrome

# запустить бота в фоне - headless: true
# запустить бота в режиме реального временеи - headless: false
headless: false

# Время паузы между поиском элементов
delay: 1

# Важно!!! Когда закончите не забывайте закрывать все процессы Firefox/Chome через диспечер задач, чтобы не грузить память
# Если остался один единственный поток который долго ожидает получения  кода можно подождать несколько секунд
# или отменить, просто закрыв программу